export enum PrinterSubState {
  NONE = 0,
  UNKNOWN = 1,

  // Printing
  P_PRINTING = 101,
  P_PRINTING_COMPLETED = 102,
  P_PAUSING = 103,
  P_PAUSED = 104,
  P_RESUMING = 105,
  P_RESUMING_COMPLETED = 106,
  P_STOPPING = 107,
  P_STOPPED = 108,

  // Preheating / Homing during print
  P_PREHEATING = 120,
  P_EXTRUDER_PREHEATING = 121,
  P_HEATED_BED_PREHEATING = 122,
  P_HOMING = 123,
  P_AUTO_LEVELING = 124,
  P_LOADING_FILAMENT = 125,
  P_UNLOADING_FILAMENT = 126,

  // Filament operations
  FO_FILAMENT_LOADING = 201,
  FO_FILAMENT_LOADING_COMPLETED = 202,
  FO_FILAMENT_UNLOADING = 203,
  FO_FILAMENT_UNLOADING_COMPLETED = 204,

  // Auto leveling
  AL_AUTO_LEVELING = 301,
  AL_AUTO_LEVELING_COMPLETED = 302,

  // PID calibration
  PC_PID_CALIBRATING = 401,
  PC_PID_CALIBRATING_COMPLETED = 402,
  PC_PID_CALIBRATING_FAILED = 403,

  // Resonance test
  RT_RESONANCE_TEST = 501,
  RT_RESONANCE_TEST_COMPLETED = 502,
  RT_RESONANCE_TEST_FAILED = 503,

  // Self-check
  SC_PID_CALIBRATING = 601,
  SC_PID_CALIBRATING_COMPLETED = 602,
  SC_PID_CALIBRATING_FAILED = 603,
  SC_RESONANCE_TEST = 610,
  SC_RESONANCE_TEST_COMPLETED = 611,
  SC_RESONANCE_TEST_FAILED = 612,
  SC_AUTO_LEVELING = 620,
  SC_AUTO_LEVELING_COMPLETED = 621,
  SC_COMPLETED = 699,

  // Updating
  U_UPDATING = 701,
  U_UPDATING_COMPLETED = 702,
  U_UPDATING_FAILED = 703,

  // Homing
  H_HOMING = 801,
  H_HOMING_COMPLETED = 802,
  H_HOMING_FAILED = 803,

  // File upload
  UF_UPLOADING_FILE = 901,
  UF_UPLOADING_FILE_COMPLETED = 902,

  // File copy
  CF_COPYING_FILE = 1001,
  CF_COPYING_FILE_COMPLETED = 1002,

  // Preheating (standalone)
  PRE_EXTRUDER_PREHEATING = 1101,
  PRE_EXTRUDER_PREHEATING_COMPLETED = 1102,
  PRE_HEATED_BED_PREHEATING = 1103,
  PRE_HEATED_BED_PREHEATING_COMPLETED = 1104,

  // Extruder operations
  EO_EXTRUDER_LOADING = 1201,
  EO_EXTRUDER_LOADING_COMPLETED = 1202,
  EO_EXTRUDER_UNLOADING = 1203,
  EO_EXTRUDER_UNLOADING_COMPLETED = 1204,
}
